blank_issues_enabled: false
contact_links:
  - name: Questions & discussion
    url: https://github.com/dimfeld/svelte-maplibre/discussions
    about: For usage questions and general discussion, please open a discussion instead of an issue.
